apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bishal-pet-deploy
  name: bishal-pet-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bishal-pet-deploy
  template:
    metadata:
      labels:
        app: bishal-pet-deploy
    spec:
      containers:
        - image: bishal1234/bishal:8
          name: bishal-pet
