apiVersion: v1
kind: Service
metadata:
  labels:
    app: bishal-pet-deploy
  name: bishal-prod-svc
  #namespace: pet
spec:
  ports:
    - port: 8089
      protocol: TCP
      targetPort: 8080
  selector:
    app: bishal-pet-deploy
  type: NodePort
